---

- hosts: webservers
  become: yes

  tasks:

    - name: install nginx latest version

      apt: update_cache=yes name=nginx state=present
    
    - name: start ningx server
      service:
        name: nginx 
        state: started

    
    - name: install php 

      apt: name={{item}} state=present

      with_items:
        - php
        - php-fpm   

    - copy: src=./default dest=/etc/nginx/sites-available/default

    - copy: src=index.php dest=/var/www/html/index.php

    - service: name=nginx state=restarted






